store_management/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.homepage),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
]

user/models.py
from django.db import models

# Create your models here.

store_management/views.py
from django.shortcuts import render, redirect, get_object_or_404

def homepage(request):
    return render(request,"page/index.html",{'page': "homepage"})

user/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request,"auth/login.html")

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django store</title>
    <link rel="stylesheet" href="/static/css/sb-admin-2.min.css">
    {% if page == 'homepage' %}
     <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
        /*
    * Globals
    */

        /* Links */
        a,
        a:focus,
        a:hover {
        color: #fff;
        }

        /* Custom default button */
        .btn-secondary,
        .btn-secondary:hover,
        .btn-secondary:focus {
        color: #333;
        text-shadow: none; /* Prevent inheritance from `body` */
        background-color: #fff;
        border: .05rem solid #fff;
        }


        /*
        * Base structure
        */

        html,
        body {
        height: 100%;
        background-color: #333;
        }

        body {
        display: -ms-flexbox;
        display: flex;
        color: #fff;
        text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
        }

        .cover-container {
        max-width: 42em;
        }


        /*
        * Header
        */
        .masthead {
        margin-bottom: 2rem;
        }

        .masthead-brand {
        margin-bottom: 0;
        }

        .nav-masthead .nav-link {
        padding: .25rem 0;
        font-weight: 700;
        color: rgba(255, 255, 255, .5);
        background-color: transparent;
        border-bottom: .25rem solid transparent;
        }

        .nav-masthead .nav-link:hover,
        .nav-masthead .nav-link:focus {
        border-bottom-color: rgba(255, 255, 255, .25);
        }

        .nav-masthead .nav-link + .nav-link {
        margin-left: 1rem;
        }

        .nav-masthead .active {
        color: #fff;
        border-bottom-color: #fff;
        }

        @media (min-width: 48em) {
        .masthead-brand {
            float: left;
        }
        .nav-masthead {
            float: right;
        }
        }


        /*
        * Cover
        */
        .cover {
        padding: 0 1.5rem;
        }
        .cover .btn-lg {
        padding: .75rem 1.25rem;
        font-weight: 700;
        }


        /*
        * Footer
        */
        .mastfoot {
        color: rgba(255, 255, 255, .5);
        }


      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    {% endif %}
</head>
<body {% if page == 'homepage' %}class="text-center"{% endif %}>
    {% block content %}{% endblock %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/sb-admin-2.min.js"></script>
</body>
</html>

templates/page/index.html
{% extends "layouts/base.html" %}
{% block content %}

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
          <div class="inner">
            <h3 class="masthead-brand">Django store</h3>
            <nav class="nav nav-masthead justify-content-center">
              <a class="nav-link active" href="#">Home</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Contact</a>
            </nav>
          </div>
        </header>
      
        <main role="main" class="inner cover">
          <h1 class="cover-heading">Django store</h1>
          <p class="lead">Application pour gerer materiel informatique</p>
          <p class="lead">
            <a href="{% url 'user:login' %}" class="btn btn-lg btn-secondary">Se connecter</a>
          </p>
        </main>
      
        <footer class="mastfoot mt-auto">
          <div class="inner">
            <p>Mini projet python 2019, Django store by Toavina, Naranja, David, Andrianina, ESTI L2 IDEV groupe 4</p>
          </div>
        </footer>
    </div>

{% endblock %}